### PR TITLE
New etcd switcher

### PR DESCRIPTION
**Pull request by AndresCidoncha**
**Changes:**

- Now the index is accesible in the root, you don't have to add the etcd version in the URL.
- New etcd switcher version
- Now the project only have 1 html. Common JS functions are moved to a common js file.

**Notes:**
- Changes on my repo updates automatically the docker image hosted in https://hub.docker.com/, you should do the same.

### CODE REVIEW

**Comment by Raboo** [comment]
@evildecay any chance this gets merged soon? I really like this feature.

**Comment by evildecay** [comment]
@Raboo I need to find time to see what was changed and check if there are any problems. Is your requirement a merged page or a docker deployment? If it is docker, I suggest you do your own docker file. I hope this project is a client tool, and docker deployment is just a way, not the only way.

**Comment by Raboo** [comment]
I was more thinking of the whole drop down selector where you can switch with v2 or v3.
So when you visit the root path of the web app you are already presented with the UI and can select which etcd version you want to connect to.

You should try Andres version and see for yourself.

And for the Docker changes, I think it's more sane to default to 0.0.0.0 as a listen address rather than 127.0.0.1 since if you default to 127.0.0.1, the UI won't be reachable from outside the docker container by default.  Why would you want to start a web service that aren't reachable? And docker within itself is isolated.

I tried @AndresCidoncha changes and I feel that none of the changes in this PR are bad for the project.

**Comment by evildecay** [comment]
@Raboo Ok, I redesigned the page based on the changes in X, and then it will become a page. I will write the document in the specific operation. The docker file will also be modified from the X version. I will re-release a version today or tomorrow. I hope I can help you.

**Comment by Raboo** [comment]
Thanks!

**Comment by evildecay** [comment]
I have updated.

**Pull request closed without merging**
